Updated flaky kuttl tests

diff --git a/test/openshift/e2e/ignore-tests/sequential/1-035_validate_argocd_secret_repopulate/05-argocd_login.yaml b/test/openshift/e2e/ignore-tests/sequential/1-035_validate_argocd_secret_repopulate/05-argocd_login.yaml
--- a/test/openshift/e2e/ignore-tests/sequential/1-035_validate_argocd_secret_repopulate/05-argocd_login.yaml
+++ b/test/openshift/e2e/ignore-tests/sequential/1-035_validate_argocd_secret_repopulate/05-argocd_login.yaml
@@ -2,15 +2,39 @@ apiVersion: kuttl.dev/v1beta1
 kind: TestStep
 commands:
 - script: |
+    # Enable error handling
+    set -e
+
+    # Get the API server route
     api_server=$(oc get routes -n openshift-gitops --field-selector metadata.name=openshift-gitops-server -o jsonpath="{.items[*]['spec.host']}")
+
+    # Check if api_server is empty
+    if [[ -z "$api_server" ]]; then
+        echo "API server is empty"
+        exit 1
+    fi
+
+    # Fetch the admin password
     password=$(oc get secret openshift-gitops-cluster -n openshift-gitops -o jsonpath='{.data.admin\.password}' | base64 -d)
+
+    # Check if password is empty
+    if [[ -z "$password" ]]; then
+        echo "Password is empty"
+        exit 1
+    fi
+
+    # Attempt to log in to ArgoCD
     output=$(argocd login $api_server --username admin --password $password --insecure)
 
+    # Check login result
     if ! [[ "${output}" =~ "'admin:login' logged in successfully" ]]; then
       if [[ "${output}" == *"rpc error: code = Unknown desc = server.secretkey is missing" ]]; then
         echo "server.secretkey is missing"
         exit 1
+      else
+        echo "Unexpected error occurred during login"
+        exit 1
       fi
     fi
-    exit 0
 
+    exit 0
